### ISSUE TITLE
Copy-TestResult : Cannot bind argument to parameter 'Files' because it is an empty array.

### ISSUE THREAD

**Issue by jmezach** [kenmuse/AzDOTestResults#1]
I'm running into the error in the title of this issue after adding the following to my pipeline:

```yml
- powershell: |
    Install-Module AzDOTestResults -Scope CurrentUser -Force -AllowClobber
    Import-Module AzDOTestResults
    Copy-TestResultToTemp
  displayName: 'Download Test Results'
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
```

The error occurs at `At C:\Users\ZEUSTFSService\Documents\WindowsPowerShell\Modules\AzDOTestResults\0.9.19\AzDOTestResults.psm1:494 char:13`. Any idea what could cause this?
